select "_fivetran_id",
       PHONE,
       STATE,
       client_name,
       session_id,
       order_id,
       shipping_address,
       payment_method,
       payment_info,
       CAST(tax_rate AS FLOAT) AS tax_rate,
       CAST(order_at AS TIMESTAMP) AS order_time,
       CAST(REGEXP_REPLACE(SHIPPING_COST, '[^0-9.]', '') AS FLOAT) AS shipping_cost,
       CAST("_fivetran_deleted" AS BOOLEAN) AS _fivetran_deleted,
       CAST("_fivetran_synced" AS TIMESTAMP) AS _fivetran_synced,
FROM {{ source('web_schema', 'orders') }}