SELECT
    "_fivetran_id",
    CAST("_fivetran_synced" AS TIMESTAMP) AS _fivetran_synced,
    CAST("_fivetran_deleted" AS BOOLEAN) AS _fivetran_deleted,
    SESSION_ID,
    ITEM_NAME,
    CAST(PRICE_PER_UNIT AS FLOAT) AS PRICE_PER_UNIT,
    CAST(ADD_TO_CART_QUANTITY AS NUMBER) AS ADD_TO_CART_QUANTITY,
    CAST(REMOVE_FROM_CART_QUANTITY AS NUMBER) AS REMOVE_FROM_CART_QUANTITY,
    CAST(ITEM_VIEW_AT AS TIMESTAMP) AS ITEM_VIEW_TIME
FROM {{ source('web_schema', 'item_views') }}